version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pickleball-court
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./templates:/app/templates
      - ./static:/app/static
    environment:
      - GIN_MODE=release
      - PORT=8000
      - TZ=UTC
      - SESSION_SECRET=${SESSION_SECRET:-your-secret-key}
      - DB_PATH=/app/data/pickleball.db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Development service with hot reload
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: pickleball-court-dev
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - go-modules:/go/pkg/mod
    environment:
      - GIN_MODE=debug
      - PORT=8000
      - TZ=UTC
      - SESSION_SECRET=${SESSION_SECRET:-your-secret-key-dev}
      - DB_PATH=/app/data/pickleball.db
    command: air
    restart: unless-stopped

volumes:
  go-modules:
